github:
  owner: ''
  repo: daily-paper-reader
arxiv_paper_setting:
  mode: standard
  days_window: 3
  docs_dir: docs
subscriptions:
  keywords:
  - keyword: Symbolic Regression
    tag: SR
    related:
    - Genetic Programming
    - Equation Discovery
    - Physics-Informed Machine Learning
    - Sparse Regression
    - Interpretable Machine Learning
    - Pareto Optimization
    rewrite: Find research papers describing the development and application of symbolic
      regression methods that leverage deep learning and evolutionary algorithms to
      discover interpretable mathematical expressions and physical laws from complex
      datasets.
  llm_queries:
  - query: 帮我去搜一些符号回归相关的论文，可以是符号回归跟其他学科相交叉的论文，可以是符号回归技术创新的论文
    tag: SR
    rewrite: Find research papers describing novel algorithmic advancements in symbolic
      regression, its interdisciplinary applications in scientific discovery, and
      performance evaluations on standard benchmarks.
  tracked_papers: []
