github:
  owner: ''
  repo: daily-paper-reader
arxiv_paper_setting:
  mode: standard
  days_window: 3
  docs_dir: docs
subscriptions:
  keywords:
    - keyword: Symbolic Regression
      tag: SR
  llm_queries:
    - query: 帮我去搜一些符号回归相关的论文，可以是符号回归跟其他学科相交叉的论文，可以是符号回归技术创新的论文
      tag: SR
  tracked_papers: []
